AllCops:
  DisabledByDefault: true
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'

Metrics/AbcSize:
  Severity: warning
Metrics/ClassLength:
  Severity: warning
Metrics/CyclomaticComplexity:
  Severity: warning
Metrics/MethodLength:
  Severity: warning
Metrics/ModuleLength:
  Severity: warning
Metrics/PerceivedComplexity:
  Severity: warning

Style/BlockDelimiters:
  EnforcedStyle: semantic
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/Next:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/SymbolArray:
  EnforcedStyle: brackets

Layout/ArgumentAlignment:
  Enabled: true
  AutoCorrect: true
  EnforcedStyle: with_fixed_indentation

Layout/BlockAlignment:
  Enabled: true
  AutoCorrect: true

Layout/BlockEndNewline:
  Enabled: true
  AutoCorrect: true

Layout/ClosingParenthesisIndentation:
  Enabled: true
  AutoCorrect: true

Layout/FirstArgumentIndentation:
  Enabled: true
  AutoCorrect: true
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  Enabled: true
  AutoCorrect: true

Layout/FirstHashElementIndentation:
  Enabled: true
  AutoCorrect: true

Layout/FirstParameterIndentation:
  Enabled: true
  AutoCorrect: true

Layout/HashAlignment:
  Enabled: true
  AutoCorrect: true

Layout/IndentationWidth:
  Enabled: true
  AutoCorrect: true

Layout/MultilineArrayLineBreaks:
  Enabled: true
  AutoCorrect: true

Layout/MultilineBlockLayout:
  Enabled: true
  AutoCorrect: true

Layout/MultilineHashBraceLayout:
  Enabled: true
  AutoCorrect: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true
  AutoCorrect: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
  AutoCorrect: true

Layout/ParameterAlignment:
  Enabled: true
  AutoCorrect: true
  EnforcedStyle: with_fixed_indentation
